/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApplicationLogo: typeof import('./resources/js/Components/UI/ApplicationLogo.vue')['default']
    AuthenticatedLayout: typeof import('./resources/js/Layouts/AuthenticatedLayout.vue')['default']
    Checkbox: typeof import('./resources/js/Components/UI/Checkbox.vue')['default']
    DangerButton: typeof import('./resources/js/Components/UI/DangerButton.vue')['default']
    Dropdown: typeof import('./resources/js/Components/UI/Dropdown.vue')['default']
    DropdownLink: typeof import('./resources/js/Components/UI/DropdownLink.vue')['default']
    GuestLayout: typeof import('./resources/js/Layouts/GuestLayout.vue')['default']
    InputError: typeof import('./resources/js/Components/UI/InputError.vue')['default']
    InputLabel: typeof import('./resources/js/Components/UI/InputLabel.vue')['default']
    Modal: typeof import('./resources/js/Components/UI/Modal.vue')['default']
    NavLink: typeof import('./resources/js/Components/UI/NavLink.vue')['default']
    PrimaryButton: typeof import('./resources/js/Components/UI/PrimaryButton.vue')['default']
    ResponsiveNavLink: typeof import('./resources/js/Components/UI/ResponsiveNavLink.vue')['default']
    SecondaryButton: typeof import('./resources/js/Components/UI/SecondaryButton.vue')['default']
    TextInput: typeof import('./resources/js/Components/UI/TextInput.vue')['default']
  }
}
